### ISSUE TITLE
: Unauthorized (HTTP 401)

### ISSUE THREAD

**Issue by jlizardi** [mkearney/kaggler#9]
input:
data <- kgl_datasets_download(owner_dataset = "secareanualin/football-events", 
                              fileName = "events.csv")

output:
Warning message: In kgl_api_get(glue::glue("datasets/download/{ownerSlug}/{datasetSlug}/{fileName}"), : Unauthorized (HTTP 401)

i get this message for every type of data pull... i think its the API... but i reset it like 3 times... any ideas?

**Comment by jlizardi** [comment]
I didnt follow the kaggle.json file / folder directions fully.

**Comment by lksprado** [comment]
@jlizardi I am getting the same error. Yesterday I was able to download but now I cant. I dont understand because I havent changed anything.
Its weird  because the kgl_auth is being able to read my credentials. What did you do?
